---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: backend
  labels:
    app: backend
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: backend
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: backend:latest
        imagePullPolicy: Always
        name: backend
        resources:
          limits:
            memory: 2048Mi
            cpu: 500m
        env:
           - name: "URL"
             value: "http://backend:3030/v1/whoami"
      restartPolicy: Always
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - backend
      from:
        kind: ImageStreamTag
        name: backend:latest
    type: ImageChange